# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreadings',
            name='moi',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
