# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_sensorreadings_moi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreadings',
            name='date',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
