# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_sensorreadings_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
                ('act', models.CharField(max_length=150)),
                ('time_stamp', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='sensorreadings',
            name='lat',
            field=models.CharField(default=13.5232, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreadings',
            name='long',
            field=models.CharField(default=79.9982, max_length=30),
            preserve_default=False,
        ),
    ]
