# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20171007_0353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activity',
        ),
        migrations.AddField(
            model_name='sensorreadings',
            name='detect',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreadings',
            name='height',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
