# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_sensorreadings_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreadings',
            name='detect',
            field=models.CharField(default='no', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreadings',
            name='level',
            field=models.CharField(default=8, max_length=30),
            preserve_default=False,
        ),
    ]
