# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20171024_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreadings',
            name='rain',
            field=models.CharField(default='no', max_length=30),
            preserve_default=False,
        ),
    ]
