# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_sensorreadings_rain'),
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('pid1', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='sensorreadings',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.plant'),
        ),
    ]
