# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20171102_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='pid1',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
