# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_auto_20171102_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='plant',
            name='longitude',
            field=models.FloatField(default=None),
        ),
    ]
