# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_auto_20171103_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreadings',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='sensorreadings',
            name='long',
        ),
    ]
